name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: latest
  POSTGRESQL_DB: postgres
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: postgres
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 54320:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Change permissions
        run: chmod +x ./mvnw
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend